var randomItems = [
  '<a id="items" data-event="hide" onclick="finalGift(\'RandomFolder/videos/finalGift0.mp4\')">Clique ici...</a>',
  '<input type="range" id="items" data-type="slider" data-event="hide" min="0" max="100" value="50" step="1">',
  'vid_graveyard-of-lovely-kittens.mp4',
  'vid_i-know-you-hate-me.mp4',
  'vid_talking-about-you.mp4',
  'vid_worthless.mp4',

  'vid_final-meldup1.mp4',

  '<p id="items">met des confetis sur l amour toujours</p>',
  '<p id="items">regarde jusqu a la fin</p>',
  '<p id="items">pour recevoir un bon cadeau</p>',
  'img_confet.png',

  '<div id="items"><a href="#" id="imageSelector">Inserer une image ici<input type="file" style="display: none;" id="imageInput" accept="image/*"></a></div>',
  '<a id="items" href="RandomFolder/specials/others/NougatinePackfromMelide-curated.zip" download="NougatinePackfromMelide-curated.zip">telecharger le sample pack Nougatine!</a>',
  
  'img_jdst.png',
  'img_pouet.png',
  'vid_loop-conffetis.mp4',

  '<p id="items" data-event="none">keep going down</p>',

  // Here's the number 1
  '<div id="items" data-event="hide" class="specialDiv"><img src="assets/numberOne.png" class="playButton" id="playButton" alt="Tas gagner"><audio autoplay id="specialAudio" controls><source src="assets/musicOne.mp3" type="audio/mpeg">Deso ya un bug screen et envoie moi en dm</audio></div>',
  // Here's the number 1

  'vid_random-slider.mp4',

  'audio_umihi-nei.mp3',
  'vid_failed-abore-me.mp4',
  'audio_deck.mp3',
  'audio_ensorcele-cover.mp3',
  
  'img_old-logo.png',
  
  'vid_avis-please.mp4',
  'vid_jcdvp-leak.mp4',
  'vid_evadls-leak.mp4',
  'audio_t-a-tahiti.mp3',

  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/3GIWrLfq1po?si=a04sBCbQyze7ayl9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/OvLl0whGBEI?si=llo1Fmekp37yV3m8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',

  'vid_firs-ever-edit.mp4',

  // Above is rare
  
  '<video controls autoplay id="items" src="RandomFolder/videos/exercice-lamour-toujours.mp4"></video>',
  'audio_moonmen-cover-2017.mp3',
  'audio_connard.mp3',
  'vid_tiens-prend-ca.mp4',
  'audio_it-is-over.mp3',
  'audio_attention-transport-disaster.mp3',
  
  'img_old-self.png',
  'img_old-self2.png',

  'vid_fuck-music-industry.mp4',
  'img_new-logo.png',

  '<iframe id="items" width="560" height="200px" src="https://www.youtube.com/embed/Nz-pRHDdfz8?si=eSdxBsfOGTSJhzly" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',

  'vid_aurevoir-leak.mp4',
  'vid_background-speedrun.mp4',
  'vid_branleur.MOV',
  'vid_ebde-la-voitue.mp4',
  'vid_quand-t-arrives-sur-gta.mp4',
  'vid_random-party-origins.mp4',
  
  'vid_code-pas-de-batterie.mp4',
  'vid_sous-la-lune.mp4',
  
  'audio_time-like-these-2017.mp3',
  'audio_dont-2019.mp3',

  'audio_inner-disgust.mp3',
  'audio_j-ride-dans-un-monde-sans-danger.mp3',
  'audio_poly-phonk.mp3',
  
  'audio_thanks-gold-version.mp3',
  'audio_thanks-old.mp3',
  
  'audio_bipbip-et-coyotte.mp3',
  'audio_cauchemart-de-nuit.mp3',
  
  'audio_i-love-you-forever.mp3',

  'vid_meldup-cashange.mp4',
  'vid_invictus-melide.mp4',
  'vid_les-petits-poissons.mp4',
  'vid_melide-ncs.mp4',
  'vid_milk-miroir.mp4',
  'vid_milk-vole.mp4',
  '<iframe id="items" width="560" height="200px" src="https://www.youtube.com/embed/Vy4UFqqZ9j8?si=1mnY8itXa1k6W35F" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
  'vid_minecraft-idv-mod.mp4',
  'vid_moi-sur-osu.mp4',
  'vid_pvz-midi.mp4',
  'vid_je-ne-t-aime-plus.MOV',

  'audio_pourquoi.mp3',
  'audio_truth-dare-live-die.mp3',
  'img_safart.jpeg',

  'vid_stupid-ai.mp4',
  'vid_video-horror-game-music.mp4',
  'vid_wsh-stromae.mp4',
  'vid_deez-nuts.mp4',
  'vid_dictio-ft-melide.mp4',
  'vid_dismembered-child.mp4',

  'vid_devine-le-son01.mp4',
  'vid_devine-le-son02.mp4',
  'vid_devine-le-son03.mp4',

  'vid_backstage-jvptp.mp4',
  'vid_backstage-tdll01.mp4',
  'vid_backstage-tdll02.mp4',

  'vid_compatibilite_PC_et_mobile.MP4',
  'vid_eiwa.MOV',
  
  'vid_chanson-pour-toi.MOV',

  'vid_final-meldup2.mp4',
  'vid_final-meldup3.mp4',

  'vid_exclu-nul1.MOV',
  'vid_ia1.MOV',
  
  
  'vid_like-pain.mp4',
  'vid_petite-video.mp4',
  'vid_rudy-talent.MOV',
  
  'special_danganronpa/danganronpa.html',
  'vid_timelapse-jonh.mp4',

  'audio_processed_happens-all-the-time.mp3',
  'audio_processed_est-elle.mp3',
  'audio_processed-lady-melody.mp3',
  'audio_processed_la-seine.mp3',

  'img_w-gouter.JPG',

  'vid_casha-drop.mp4',

  'audio_dubidubi.mp3',
  'audio_mine-prod-super-clean.mp3',
  'audio_philophobia.mp3',

  'vid_failed-animation.mp4',
  'vid_failed-danganronpa.mp4',
  'vid_failed-danganronpa-death.mp4',
  'vid_failed-depressed-melide.mp4',
  'vid_failed-depressed-melide-2.mp4',
  'vid_failed-hyper-hype.mp4',
  'vid_failed-just-a-dream.mp4',
  'vid_failed-melide-skrillex.mp4',
  'vid_failed-melody.mp4',
  'vid_failed-pluie.mp4',
  'vid_failed-script.mp4',
  'vid_failed-video-game.mp4',
  'vid_failed-visual-novel.mp4',
  'vid_failed-worst-animations.mp4',
  'audio_failed-vacances.mp3',

  'audio_dessin-anijeu.mp3',

  'img_aesthetic.jpg',
  'img_bg.jpg',
  'img_cafe.PNG',
  'img_cannot-record.jpg',
  'img_childhood-courtyard.PNG',
  'img_choco-milk.JPG',
  'img_concept-attd.PNG',
  'img_fantasies.jpeg',
  'img_concept-lorange.jpg',
  'img_denji-et-moi.JPG',
  'img_dessin0.PNG',
  'img_doigt.PNG',
  'img_elle-m-aime.PNG',
  'img_est-elle.PNG',
  'img_ff7.PNG',
  'img_guitar-plage.PNG',

  'vid_perdu.mp4',

  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/8ySf6onNJ28?si=GIfqGH_h3ZPOCquz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/gwZJ1M1dQV4?si=BPjIcIaLyIlrYN4X" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/iDGFV6r_Weo?si=kromQxNAjq6nP_io" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/q9rv-Cq-gTM?si=tWoSnMggbpc3RPTv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/nHu0ADgtiWU?si=p3mg4CIxTZfhjPbn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/QzKgVTMtikc?si=_leLFyTYItlUa55B" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/dtywgPE3Msc?si=lZeI4jd1pHHAjo3O" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/KSX_mcz4fN0?si=X7D4_o5qjrz_hfk6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/mgo1OFGPEFM?si=vQd_lEQGjjhgrYOx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/fJy_SMUqlGg?si=RUSZoDUZghMB_BEa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/K7CzwZymf4w?si=f4iTdF5lBH36Qh8a" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/RuqgbWJ___g?si=Qth3WHOTABEFFmVE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/Nv81QtAlQb8?si=EEJ5lsjykdmOmUl3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  
  
  
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/wC9mKvSdN70?si=jneBsmIGNkhMJvbJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/ktN_6LdAVH8?si=2C-X-eh7433pwvMl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/bi5PFCAhdV4?si=SQ9C5Mi_QWPM6FCo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/XAW8tatYUgA?si=sNaC0QO1gjUE4g_Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/ycg1sG2Gz4Q?si=HovN4LoBBxxXD0U9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/oWB67WVZ_7w?si=H4MiGOB96RyeEGSy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/NhTKT5IISKA?si=TWa69PdXSxSpBj-8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/sXvFfdGhQIM?si=SOgA3rsGi8khvvjv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/EfyXOdvmI9g?si=t4YUVctonuJO3PQf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/NKD-16_7njw?si=fxjwFLdxhuDhkpGE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',
  '<div id="items" data-event="none"><iframe width="560" height="200px" src="https://www.youtube.com/embed/pmShpnpyPYc?si=7tj1YuvZHiK7bQge" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>',

  'img_hello.PNG',
  'img_huh.JPG',
  'img_jeu-video.PNG',
  'img_kitkat.jpg',
  'img_lara-wip.JPG',
  'img_lara.jpg',
  'img_le-ciel.jpg',
  'img_le-pc.jpg',
  'img_les-betises.jpg',
  'img_les-potentiels-sons.jpg',
  'img_ma-chambre.jpg',
  'img_maman.jpg',
  'img_mc-render.JPG',
  'img_melide-render0.PNG',
  'img_melide-render1.PNG',
  'img_melide-render2.jpg',
  'img_merci1.jpg',
  'img_merci2.jpg',
  'img_merci3.jpg',
  'img_merci4.PNG',
  'img_my-island.jpg',
  'img_nostalgia.JPG',
  'img_nostalgia1.PNG',
  'img_nostalgia2.PNG',
  'img_nostalgia4.jpg',
  'img_nostalgia5.jpg',
  'img_patate.PNG',
  'img_pc-opening.JPG',
  'img_pixel-war.JPG',
  'img_plan-maison.PNG',
  'img_plight.PNG',
  'img_proj-t0.JPG',
  'img_puatoro.png',
  'img_random-beau.jpg',
  'img_releve-bancaire.JPG',

  'img_blocked.png',
  'img_old-memories.jpeg',
  'img_peace.jpeg',
  'img_random-last-rare.jpeg',
  'img_thanks.jpeg',

  'img_cool-art.jpg',
  'img_crescent-melide.PNG',
  'img_euh.PNG',
  'img_euuh.JPG',
  'img_game-dev-ios.JPG',
  'img_game-render.JPG',
  'img_lapin.JPG',
  'img_milk-pref.jpg',
  'img_mini-john.jpg',
  'img_pipopipo.JPG',

  'img_spotify-banner.PNG',
  'img_t-douce.jpg',
  'img_t-trop-cute.JPG',
  'img_uwu-model.JPG',
  'img_wip-demons.jpg',
  'img_wip-ttd.PNG',
  'img_yoda-zach.JPG',

  'img_wassup.JPG',
  'img_ytb-banner.PNG',
  'img_souvenir.JPG',
  'img_roi.PNG',

  'img_glandDeMilk.jpeg',
  'img_idv.jpeg',

  '<button id="items" class="btn" data-event="none" onclick="createRandomItem()">Appuie sur le bouton</button>',
  '<img id="items" data-event="hide" src="RandomFolder/images/hint0b.png">',

  // Last hints
  '<video controls id="items" data-event="hide" src="RandomFolder/videos/hint0.mp4"></video>',
  '<video controls id="items" data-event="hide" src="RandomFolder/videos/hint1.mp4"></video>',

  // Hidden hints
  '<p id="items" data-event="hide">user = admin</p>',
  '<p id="items" data-event="hide">password = nimda</p>'
];

var randomQuotes = {
  '-14': 'Zombi in the kitchen - graveyard of lovely kittens',
  '-13': 'i know you hate me (new attempt)',
  '-12': 'Zombi in the kitchen - I knew it (attempt, demo)',
  '-11': 'Zombi in the kitchen - worthless',
  '-6': 'ah bon?',
  '-1': 'Cest jolie en vrai',
  1: 'BRAVO CONFETTIS YAY',
  3: 'Cette musique cest la première que je fais avec mon frère. Cette musique est très cher à mes yeux en sachant les relations que jai eu avec lui. Love you brother <3',
  4: 'Dites moi hônnetement si vous aimez ce style de musique car perso ça me met des frissons.',
  5: 'MES PREMIERS REMIX TAHITIENS',
  6: 'Lorie - Ensorcelée ( Melide Cover )   musique de quand jétais bébé et jmen souviens trop bien jen ai les frissons',
  7: 'Lancien logo de 2017, je crois lavoir changé en 2019',
  8: 'EXCLU: dites moi en dm si vous la voulez en entière <3',
  9: 'DISPO SUR TOUTES LES PLATEFORMES: Melide - Jai cesser de vous plaire (avec la faute oui)',
  10: 'DISPO SUR TOUTES LES PLATEFORMES: Melide - Elle veut aller dans les states',
  11: '"T à Tahiti" ça devait sortir avec les trois autres sons, mais celui là je trouvais moins abouti, donc je le referais pour un futur projet!',
  12: 'Je sais pas si vous aimez bien ce genre de vibe, venez me dire en dm si cest votre truc',
  13: 'Jétais Youtubeur oui',
  14: 'Mon tout premier edit ever, vous savez cest quoi lanime? Jaimerais bien le retrouver pls',
  15: 'LAMOUR TOUJOURS',
  16: 'Moonmen cover du Melide de 15 ans',
  17: 'edileM - C O N N A R D',
  18: 'Je kiff retrouver mon ami denfance et découvrir gta online avec lui',
  19: '2019Melide - Its over',
  20: 'Melide - Transport Disaster (main theme)',
  21: 'Cette photo, bien quordinaire, signifie le plus gros changement de ma vie. Cest le jour où jai compris à 14 ans que je nétais pas foutu',
  22: 'Ce jour là on a mangé une pizza incroyable avec ma mère et mon grand frère, il a pris des photos de moi en ce foutant de ma gueule parce que "on dirait un zombi qui découvre la lumière" mais on a kiffer ensemble pour une fois :)',
  25: 'Jétais youtubeur cringe, mais talentueux',
  26: 'JE SAIS HÔNNETEMENT PAS SI CEST BIEN, DITES MOI EN DM SI CEST BEIN',
  28: 'Melide - Connasse de directrice (jla refais?)',
  29: 'Mon ami qui comprend que jsuis nul sur gta et me traque à moto volante mais cest lui qui fail (ce roi)',
  30: 'quand tarrives sur gta online :,)',
  31: 'si je me trompe pas, ça cest le prototype du tout premier site random assisté par gpt',
  32: 'speedrun du code de la page dacceuil',
  33: 'Melide - Sous les lumières (prévu que je la refasse)',
  34: 'Time like these ( Melide Cover de 2017 )',
  35: 'Melide - Dont ( Horrible World update theme )',
  36: 'edileM - l a   f i n a l i t é',
  37: 'edileM - j r i d e   d a n s   u n   m o n d e   s a n s   d a n g e r',
  38: 'edileM - a t a   n o a',
  39: '"Melide - Thanks" x "Zombi in the kitchen - Thanks"',
  40: 'old Thanks is gold',
  41: 'edileM - b i p   b i p   e t   c o y o t t e',
  42: 'free instru - Cauchemar de nuit ( from 2020 i guess )',
  43: 'Melide - i love you forever',
  44: 'Jai écris le texte et ils ont PERFORME MON AUDIO JE SUIS EPOUSTOUFLE F DANS LE CHAT POUR RESPECTER (faut je credit cashalot cetace sur insta et sa chérie)',
  45: 'Oui, jai bien composé une musique de pub (qui na jamais été utilisé)',
  47: 'aller harceler ncs pour que je poste la musique sur leurs chaîne svp',
  48: 'milk - miroir (jai produis)',
  49: 'milk dans les nuages comme à son habitude car cest son environment naturel :3',
  50: 'Melide - Miroir (jai fait ça pour ma meilleure amie pour son univers mais elle a changé son univers donc pg ca fait une belle musique<3)',
  51: 'jai modé Minecraft pour refaire le jeu Identity V dedans',
  52: 'moi sur osu et quand jentend chipi chipi chapa chapa',
  53: 'jai codé un programme pour faire la melodie de pvz',
  54: 'Melide - Je ne taime plus',
  55: 'free instru - pourquoi',
  56: 'Melide - truth or dare live or die (pour un jeu vidéo horreur)',
  57: 'en pleine session de chant stay cool <3',
  58: 'eux: les ia vont dominer le monde!      the ia in question:',
  59: 'ca devait être pour un jeu personnel mais pg <3',
  60: 'jfais une instru comme ci jétais stromae ou quoi',
  61: 'deez nuts',
  62: 'feat avec dictio annulé je pense mais donnez lui de le force please!',
  63: 'Melide - Dismembered Child ( fais pour une pote trop talentueuse )',
  64: 'celui qui trouve doù ça vient jloffre un diner',
  65: 'celui qui trouve doù ça vient jloffre un mcdo de son choix (sauf si tes denji tomy)',
  66: 'celui qui trouve doù ça vient vous me ferez lun des meilleurs cadeau de ma vie',
  67: 'Les backstage de Je veux pas te perdre (cest illegal je crois)',
  68: 'BEHIND THE SCENE - Tout doux, Démons',
  69: 'BEHIND THE SCENE - Tout doux, Démons',
  70: 'je code assez bien en vrai en si peu de temps (1 journée de code)',
  72: 'wah cest cringe mais jmennuyais... (la friendzone oui)',
  73: 'non vraiment pourquoi...',
  74: '<3333333',
  75: 'jai un abonnement à la depression',
  77: 'Melide - The Pain ( ça date celle là jcrois de 2018 )',
  78: 'Je vous expose pour la première fois ma tête féliciter moi',
  79: 'On devais faire ce son avec Rudynosaure, je rêve encore de faire un son calme avec lui',
  82: 'H appens all the time',
  83: 'E st elle',
  84: 'L ady Mélodie',
  85: 'L a Seine',
  86: 'repas du champion (de 2017 jsuis choqué de lancienneté de cette photo)',
  87: 'jvoulais faire ce drop mais casha naimais pas ;(',
  88: 'CHIPI CHIPI CHAPA CHAPA DUBI DUBI DABA DABA MAGICO MI DUBI DUBI BOOM BOOM BOOM BOOM',
  89: 'jlai deja mis lannée dernière mais jai à 100% créer cette musique et jen suis trop fier',
  90: 'instru - Philophobia',
  91: 'les débuts de mes animations vraiment',
  92: 'Je devais faire un fan game de Danganronpa mais les gens sont méchants avec moi',
  93: 'death scene danganronpa 0.0',
  94: 'je crois cest la dépression qui est abonnée à moi... dsl',
  95: 'non vraiment jcrois je suis la dépression de la dépression elle même',
  96: 'high energy going nowhere as a slot machine',
  97: 'vous aimez bien ce genre de vibe??',
  98: 'Je devais aussi concurrencé Skrillex mais bon jsuis timide uwu',
  99: 'je chiale',
  100: 'musique de pub de shampoing',
  101: 'japprenais à coder uwu',
  102: 'ce code est assez surpuissant, sachant quil a été fait sur mobile',
  104: 'je code bien, mais les animations sont à chier...',
  105: 'Melide - On attends les vacances (mais on ma dit que cétait nul)',
  106: 'Un dessin animé sur Melide mdrrrr',
  108: 'jetais correct olala',
  111: 'venez faire un studio de jeu avec moi',
  113: 'jplanifie encore de faire ce jeu, ca pourrait être banger',
  114: 'comfort characters <3333',
  115: 'Ce site aurait pu être révolutionnaire',
  116: 'Denji on termine fvgl ou jle termine seul?',
  117: 'petit dessin',
  118: 'grosse blessure du doigt',
  119: 'jveux utiliser cette cover si je fais une musique qui sappelle "Elle est"',
  120: 'Est elle supremacy',
  121: 'vous connaissez le meilleur jeu au monde? indice : ce nest pas Cloud sur la photo',
  123: 'c beau?',
  124: 'nul mais oui jvous aimes',
  125: 'ca date',
  126: 'on ma dit que cette musique etait nulle',
  128: 'cest fun comme instru',
  129: 'vibe xbox360',
  130: 'soit on le fini avec denji soit jle fini',
  131: 'outro de dessin anime clairement',
  133: 'jspp si milk aimait bien ce son',
  135: 'plus jamais je fais de son comme ça... même si cest fire à la fin',
  137: 'osez me dire que je nai pas capter la vibe minecraft hivernale',
  138: 'la mélodie est fire mais le drop est nul vrm...',
  141: 'avoue tas envie denquêter quand tentend cette musique',
  142: 'retournement leger de situation dans le dangan',
  143: 'instru pour des gens que jaime et qui sont malgré eux addicts à la cigarette',
  144: 'Melide - They Left Us ( main theme )   ce jeu aurait pu être bien en sah ambiance pensionnat de sarlat mélangé à Tim Burton',
  145: 'jétais youtubeur',
  146: 'je suis herlock sholmes',
  147: 'contacter ncs ou dropnation pour quil me mette sur leurs chaîne par pitié...',
  152: 'wip de lara',
  153: 'lara finie et magnifique <3',
  157: 'ce que devait être la liste des musiques',
  159: 'maman <333',
  160: 'OMG JSUIS UN YOUTUBEUR MINECRAFT MTN',
  161: 'hello',
  162: 'are you watching me?',
  164: 'merci elo vrm <3333333',
  165: 'merci milku tres fort <3',
  166: 'vrm le bonheur quand je vois que cetait une bonne idéé la derniere fois, merci beaucoup <33',
  167: 'merci rudy puréé jespere tu seras au rdv cette fois aussi!',
  168: 'my island <3',
  169: 'my old room <3',
  172: 'lherbe au centre de formation, dedicace à Bernard jte kiff mon ami <3',
  176: 'i was there fighting for France',
  177: 'le plan de ma maison si vous voulez me cambrioler',
  178: 'Plight',
  180: 'DINGUERIE CE PLAT DE CHEZ MOI',
  181: 'Random',
  186: 'et nous voilà ici aujourdhui',
  195: 'cest mon image preferée de milk',
  196: 'c moi :3',
  197: 'il était là lannée dernière, il est là aujourdhui',
  199: 'lamour mas sauver <3',
  200: 'jure tu connais ce son',
  201: 'mon premier model blender',
  203: 'ATTD work in progress',
  204: 'dédicace à zach on as fait un sandwich de la terre',
  209: 'vous avez perdu votre gland de lait à quel âge vous?'
};

var randomSongCover = {
  'processed_est-elle.mp3': 'help.png',
  'processed_happens-all-the-time.mp3': 'help.png',
  'processed_la-seine.mp3': 'help.png',
  'processed-lady-melody.mp3': 'help.png',

  'dessin-anijeu.mp3': 'dessin-anijeu-gif.gif',

  't-a-tahiti.mp3': 't-a-tahiti.png',
  
  'attention-transport-disaster.mp3':'attd.png',
  'deck.mp3':'deck.png',
  'dubidubi.mp3':'dubidubi.png',
  'ensorcele-cover.mp3':'ensorcele.png',
  'moonmen-cover-2017.mp3':'moonmen.png',
  'thanks-old.mp3':'thanks.png',
  'thanks-gold-version.mp3':'thanks.png',
  'umihi-nei.mp3':'umihinei.png',

  'bipbip-et-coyotte.mp3':'global-phonk.png',
  'connard.mp3':'global-phonk.png',
  'inner-disgust.mp3':'global-phonk.png',
  'j-ride-dans-un-monde-sans-danger.mp3':'global-phonk.png',
  'poly-phonk.mp3':'global-phonk.png',
}
