var randomItems = [
  '<a id="items" data-event="hide" onclick="createRandomItem()">Clique ici</a>',
  '<input type="range" id="items" data-type="slider" data-event="hide" min="0" max="100" value="50" step="1">',
  '<button id="items" class="btn" data-event="none">Appuie sur le bouton</button>',
  '<img id="items" src="assets/silly-cat-holder.png" data-event="none">',
  'img_aesthetic.jpg',
  'img_bg.jpg',
  'img_cafe.PNG',
  'img_cannot-record.jpg',
  'img_childhood-courtyard.PNG',
  'img_choco-milk.JPG',
  'img_concept-attd.PNG',
  'img_concept-lorange.jpg',
  'img_denji-et-moi.JPG',
  'img_dessin0.PNG',
  'img_doigt.PNG',
  'img_elle-m-aime.PNG',
  'img_est-elle.PNG',
  'img_ff7.PNG',
  'img_guitar-plage.PNG',
  'img_hello.PNG',
  'img_huh.JPG',
  'img_jeu-video.PNG',
  'img_kitkat.jpg',
  'img_lara-wip.JPG',
  'img_lara.jpg',
  'img_le-ciel.jpg',
  'img_le-pc.jpg',
  'img_les-betises.jpg',
  'img_les-potentiels-sons.jpg',
  'img_ma-chambre.jpg',
  'img_maman.jpg',
  'img_mc-render',
  'img_melide-render0.PNG',
  'img_melide-render1.PNG',
  'img_melide-render2.jpg',
  'img_merci1.jpg',
  'img_merci2.jpg',
  'img_merci3.jpg',
  'img_merci4.PNG',
  'img_my-island.jpg',
  'img_nostalgia.JPG',
  'img_nostalgia1.PNG',
  'img_nostalgia2.PNG',
  'img_nostalgia4.jpg',
  'img_nostalgia5.jpg',
  'img_patate.PNG',
  'img_pc-opening.JPG',
  'img_pixel-war.JPG',
  'img_plan-maison.PNG',
  'img_plight.PNG',
  'img_proj-t0.JPG',
  'img_puatoro.png',
  'img_random-beau.jpg',
  'img_releve-bancaire.JPG',

  'img_cool-art.jpg',
  'img_crescent-melide.PNG',
  'img_euh.PNG',
  'img_euuh.JPG',
  'img_game-dev-ios.JPG',
  'img_game-render.JPG',
  'img_lapin.JPG',
  'img_milk-pref.jpg',
  'img_mini-john.jpg',
  'img_pipopipo.JPG',
  'img_spleef.PNG',
  'img_spotify-banner.PNG',
  'img_t-douce.jpg',
  'img_t-trop-cute.JPG',
  'img_uwu-model.JPG',
  'img_wip-demons.jpg',
  'img_wip-ttd.PNG',
  'img_yoda-zach.JPG'
];

var randomQuotes = {};
