var randomItems = [
  '<a id="items" data-event="hide" onclick="finalGift()">Clique ici...</a>',
  '<input type="range" id="items" data-type="slider" data-event="hide" min="0" max="100" value="50" step="1">',
  'Z',
  'O',
  'M',
  'B',
  'I',

  '',
  '',

  '',
  '',
  '',

  '',
  '',
  '',
  '',
  '',

  // Here's the number 1
  '<a id="items" data-event="hide"></a>',

  '<button id="items" class="btn" data-event="none">Appuie sur le bouton</button>',
  '<img id="items" src="assets/silly-cat-holder.png" data-event="none">',

  'vid_ebde-la-voitue.mp4',
  'vid_quand-t-arrives-sur-gta.mp4',
  'vid_tiens-prend-ca.mp4',
  'vid_final-meldup1.mp4',
  'vid_final-meldup2.mp4',
  'vid_final-meldup3.mp4',

  'vid_random-slider.mp4',
  'vid_meldup-cashange.mp4',

  'vid_aurevoir-leak.mp4',
  'vid_background-speedrun.mp4',
  'vid_branleur.MOV',

  // Above is rare
  'vid_chanson-pour-toi.MOV',
  'vid_code-pas-de-batterie.mp4',

  'vid_failed-abore-me.mp4',
  'vid_failed-animation.mp4',
  'vid_failed-danganronpa.mp4',
  'vid_failed-danganronpa-death.mp4',
  'vid_failed-depressed-melide.mp4',
  'vid_failed-depressed-melide-2.mp4',
  'vid_failed-hyper-hype.mp4',
  'vid_failed-just-a-dream.mp4',
  'vid_failed-melide-skrillex.mp4',
  'vid_failed-melody.mp4',
  'vid_failed-pluie.mp4',
  'vid_failed-script.mp4',
  'vid_failed-video-game.mp4',
  'vid_failed-visual-novel.mp4',
  'vid_failed-worst-animations.mp4',
  'vid_fuck-music-industry.mp4',
  'vid_invictus-melide.mp4',
  'vid_les-petits-poissons.mp4',
  'vid_melide-ncs.mp4',
  'vid_milk-miroir.mp4',
  'vid_milk-vole.mp4',
  'vid_minecraft-idv-mod.mp4',
  'vid_moi-sur-osu.mp4',
  'vid_pvz-midi.mp4',
  'vid_random-party-origins.mp4',

  'vid_sous-la-lune.mp4',
  'vid_stupid-ai',
  'vid_video-horror-game-music.mp4',
  'vid_wsh-stromae.mp4',
  'vid_deez-nuts.mp4',
  'vid_dictio-ft-melide.mp4',
  'vid_dismembered-child.mp4',

  'vid_devine-le-son01.mp4',
  'vid_devine-le-son02.mp4',
  'vid_devine-le-son03.mp4',

  'vid_backstage-jvptp.mp4',
  'vid_backstage-tdll01.mp4',
  'vid_backstage-tdll02.mp4',

  'vid_compatibilite_PC_et_mobile.MP4',
  'vid_eiwa.MOV',
  'vid_evadls-leak.mp4',
  'vid_exclu-nul1.MOV',
  'vid_ia1.MOV',
  'vid_jcdvp-leak.mp4',
  'vid_je-ne-t-aime-plus.MOV',
  'vid_like-pain.mp4',
  'vid_petite-video.mp4',
  'vid_rudy-talent.MOV',
  
  'special_danganronpa/danganronpa.html',

  'audio_processed_happens-all-the-time.mp3',
  'audio_processed_est-elle.mp3',
  'audio_processed-lady-melody.mp3',
  'audio_processed_la-seine.mp3',

  'img_aesthetic.jpg',
  'img_bg.jpg',
  'img_cafe.PNG',
  'img_cannot-record.jpg',
  'img_childhood-courtyard.PNG',
  'img_choco-milk.JPG',
  'img_concept-attd.PNG',
  'img_concept-lorange.jpg',
  'img_denji-et-moi.JPG',
  'img_dessin0.PNG',
  'img_doigt.PNG',
  'img_elle-m-aime.PNG',
  'img_est-elle.PNG',
  'img_ff7.PNG',
  'img_guitar-plage.PNG',
  'img_hello.PNG',
  'img_huh.JPG',
  'img_jeu-video.PNG',
  'img_kitkat.jpg',
  'img_lara-wip.JPG',
  'img_lara.jpg',
  'img_le-ciel.jpg',
  'img_le-pc.jpg',
  'img_les-betises.jpg',
  'img_les-potentiels-sons.jpg',
  'img_ma-chambre.jpg',
  'img_maman.jpg',
  'img_mc-render',
  'img_melide-render0.PNG',
  'img_melide-render1.PNG',
  'img_melide-render2.jpg',
  'img_merci1.jpg',
  'img_merci2.jpg',
  'img_merci3.jpg',
  'img_merci4.PNG',
  'img_my-island.jpg',
  'img_nostalgia.JPG',
  'img_nostalgia1.PNG',
  'img_nostalgia2.PNG',
  'img_nostalgia4.jpg',
  'img_nostalgia5.jpg',
  'img_patate.PNG',
  'img_pc-opening.JPG',
  'img_pixel-war.JPG',
  'img_plan-maison.PNG',
  'img_plight.PNG',
  'img_proj-t0.JPG',
  'img_puatoro.png',
  'img_random-beau.jpg',
  'img_releve-bancaire.JPG',

  'img_blocked.png',
  'img_old-memories.jpeg',
  'img_peace.jpeg',
  'img_random-last-rare.jpeg',
  'img_thanks.jpeg',

  'img_cool-art.jpg',
  'img_crescent-melide.PNG',
  'img_euh.PNG',
  'img_euuh.JPG',
  'img_game-dev-ios.JPG',
  'img_game-render.JPG',
  'img_lapin.JPG',
  'img_milk-pref.jpg',
  'img_mini-john.jpg',
  'img_pipopipo.JPG',
  'img_spleef.PNG',
  'img_spotify-banner.PNG',
  'img_t-douce.jpg',
  'img_t-trop-cute.JPG',
  'img_uwu-model.JPG',
  'img_wip-demons.jpg',
  'img_wip-ttd.PNG',
  'img_yoda-zach.JPG',

  'img_wassup.JPG',
  'img_ytb-banner.PNG',
  'img_souvenir.JPG',
  'img_roi.PNG',

  // Last hints
  '<p id="items" data-event="hide">wait</p>',
  '<p id="items" data-event="hide">wait</p>'
];

var randomQuotes = {};

var randomSongCover = {
  'processed_est-elle.mp3': 'help.png',
  'processed_happens-all-the-time.mp3': 'help.png',
  'processed_la-seine.mp3': 'help.png',
  'processed-lady-melody.mp3': 'help.png',
}